feito a class Professor e o endpoint de criar professor
future4code/Carver-labenu-system17 pull request #2
Opened 2022-02-17 21:58 UTC by yMarceloMaia

POR FAVOR, EDITE ESSA MENSAGEM INSERINDO AS INFORMAÇÕES DO SEU PROJETO. COMECE APAGANDO ESSA LINHA.

### INSIRA O NOME NOME DO PROJETO AQUI

### O que funciona
- DESCREVA O QUE FUNCIONA NO SEU PROJETO

### O que não funciona
- DESCREVA O QUE NÃO FUNCIONA NO SEU PROJETO

### Link Surge 
A PARTIR DA SEMANA 5, INSIRA AQUI O LINK DO SURGE. **ANTES DISSO, APAGUE ESSAS DUAS LINHAS.**

### Imagens
TIRE PRINTS DAS TELAS DO SEU SITE E COLE AQUI

2022-02-17 22:30 UTC, Leozartino requested changes

2022-02-17 22:30 UTC, Leozartino commented on src/controllers/professor.controller.ts
> +        const checkClassId = await connection()
Acho que falta uma validação pra verificar se o classID existe

2022-02-17 22:30 UTC, Leozartino commented on src/controllers/professor.controller.ts
> +        res.status(200).end()
Aqui poderia ficar o status 201 pra retorno de "created sucessfully"

2022-02-18 15:05 UTC, yMarceloMaia commented on src/controllers/professor.controller.ts
> +        res.status(200).end()
é mesmo, vou mudar lá

2022-02-18 15:06 UTC, yMarceloMaia commented on src/controllers/professor.controller.ts
> +        const checkClassId = await connection()
tentei fazer essa validação, mas quando eu mandava um id inexistente, já aparecia um erro vindo do banco de dados

2022-02-18 18:13 UTC, Leozartino approved these changes

2022-02-18 18:13 UTC, merged